     BUN     LOADER_MAIN
     BUN     ISR
 LOADER_MAIN, ION
 LOAD_LOOP,BSA  READ_WORD
     STA     PROG_SIZE
     BSA     LOAD_PROGRAM
     BSA     PROGRAM_BASE
     BUN     LOAD_LOOP
LOAD_PROGRAM, HEX 0
    LDA     ZERO
    STA     LOAD_INDEX
LOAD_PROGRAM_LOOP,
    LDA LOAD_INDEX
    SUB     PROG_SIZE
    SPA
    BUN     LOAD_DONE
    BSA     READ_WORD
    STA     TEMP_DATA
    LDA     LOAD_INDEX
    ADD     PROGRAM_BASE
    STA     TEMP_ADDR
    LDA     TEMP_DATA
    STA     TEMP_ADDR I
    LDA     LOAD_INDEX
    INC
    STA     LOAD_INDEX
    BUN     LOAD_PROGRAM_LOOP
LOAD_DONE, BUN LOAD_PROGRAM I
    ORG     100
READ_WORD, HEX 0
WAIT_FOR_INPUT, LDA INPUT_READY
    SZA
    BUN     HAVE_INPUT
    BUN     WAIT_FOR_INPUT
HAVE_INPUT,
    LDA     INPUT_BUFFER
    STA     TEMP_DATA
    LDA     ZERO
    STA     INPUT_READY
    LDA     TEMP_DATA
    BUN     READ_WORD I
    ORG     150
WRITE_WORD, HEX 0
    STA     OUTPUT_DATA
    LDA     ONE
    STA     OUTPUT_PENDING
WAIT_FOR_OUTPUT,
    LDA OUTPUT_PENDING
    SZA
    BUN     WAIT_FOR_OUTPUT
    BUN     WRITE_WORD I
    ORG     200
ISR,    STA    SAVE_AC
    SKI
    BUN     CHECK_OUTPUT
    INP
    STA     INPUT_BUFFER
    LDA     ONE
    STA     INPUT_READY
    BUN     ISR_EXIT
CHECK_OUTPUT, SKO
    BUN     ISR_EXIT
    LDA     OUTPUT_PENDING
    SZA
    BUN     PERFORM_OUTPUT
    BUN     ISR_EXIT
PERFORM_OUTPUT,
    LDA OUTPUT_DATA
    OUT
    LDA     ZERO
    STA     OUTPUT_PENDING
ISR_EXIT, LDA   SAVE_AC
    BUN     0 I
    ORG     250
ZERO,           DEC 0
ONE,            DEC 1
PROG_SIZE,      DEC 0
LOAD_INDEX,     DEC 0
TEMP_ADDR,      HEX 0
TEMP_DATA,      DEC 0
INPUT_BUFFER,   DEC 0
INPUT_READY,    DEC 0
OUTPUT_DATA,    DEC 0
OUTPUT_PENDING, DEC 0
SAVE_AC,        DEC 0
PROGRAM_BASE,   HEX 300
        END

  ORG 300 ; User program
USER_ENTRY, HEX 0
  BSA 100
  ADD TEN
  BSA 150
  BUN USER_ENTRY I
  TEN, DEC 10
  END

; Developed with assistance from DeepSeek, Grok, Gemini and Grok AI for educational purposes in OS course slides
; Program with Procedure Vector Table (like interrupt vectors)
; Uses polling I/O with indirect BSA calls

