// The code is generated by DeepSeek before editing
// Interrupt_Driven_Program_with_BSA_Subroutines.asm

        ORG     0
        BUN     MAIN
        BUN     ISR

MAIN,   LDA     ZERO
        STA     COUNT
        ION

WORK,   LDA     COUNT
        INC
        STA     COUNT
        BUN     WORK

ISR,    STA     SAVE
        BSA     IO
        ION
        LDA     SAVE
        BUN     0  I

IO,     HEX     0
        SKI
        BUN     OUTPUT
        INP
        STA     BUFFER
        BUN     IO  I
OUTPUT, SKO
        BUN     IO  I
        OUT
        BUN     IO  I

ZERO,   DEC     0
COUNT,  DEC     0
SAVE,   DEC     0
BUFFER, DEC     0
        END