
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPAR MUL NUMBER PLUS RPARS : EE : E PLUS TE : TT : T MUL FT : FF : NUMBERF : LPAR E RPAR'
    
_lr_action_items = {'NUMBER':([0,6,7,8,],[5,5,5,5,]),'LPAR':([0,6,7,8,],[6,6,6,6,]),'$end':([1,2,3,4,5,10,11,12,],[0,-1,-3,-5,-6,-2,-4,-7,]),'PLUS':([2,3,4,5,9,10,11,12,],[7,-3,-5,-6,7,-2,-4,-7,]),'RPAR':([3,4,5,9,10,11,12,],[-3,-5,-6,12,-2,-4,-7,]),'MUL':([3,4,5,10,11,12,],[8,-5,-6,8,-4,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'E':([0,6,],[2,9,]),'T':([0,6,7,],[3,3,10,]),'F':([0,6,7,8,],[4,4,4,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> E','S',1,'p_S','ply_calc220_code.py',28),
  ('E -> E PLUS T','E',3,'p_E_plus_T','ply_calc220_code.py',32),
  ('E -> T','E',1,'p_E_T','ply_calc220_code.py',43),
  ('T -> T MUL F','T',3,'p_T_MUL_F','ply_calc220_code.py',47),
  ('T -> F','T',1,'p_T_F','ply_calc220_code.py',58),
  ('F -> NUMBER','F',1,'p_F_a','ply_calc220_code.py',62),
  ('F -> LPAR E RPAR','F',3,'p_F_lpar_E_rpar','ply_calc220_code.py',68),
]
